In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
# data = {
#     'Age': [18, 19, 20, 18, 21, 22, 19, 20, 23, 18],
#     'Study_Hours': [2, 4, 5, 3, 6, 8, 4, 5, 7, 2],
#     'Final_Score': [55, 65, 72, 60, 78, 90, 68, 75, 85, 58],
#     'Gender': ['Male', 'Female', 'Female', 'Male', 'Female',
#                'Male', 'Male', 'Female', 'Male', 'Female']
# }

In [ ]:
# df = pd.DataFrame(data)
# df

   Age  Study_Hours  Final_Score  Gender
0   18            2           55    Male
1   19            4           65  Female
2   20            5           72  Female
3   18            3           60    Male
4   21            6           78  Female
5   22            8           90    Male
6   19            4           68    Male
7   20            5           75  Female
8   23            7           85    Male
9   18            2           58  Female

In [ ]:
# df.info

<bound method DataFrame.info of    Age  Study_Hours  Final_Score  Gender
0   18            2           55    Male
1   19            4           65  Female
2   20            5           72  Female
3   18            3           60    Male
4   21            6           78  Female
5   22            8           90    Male
6   19            4           68    Male
7   20            5           75  Female
8   23            7           85    Male
9   18            2           58  Female>

In [ ]:
# df.describe()

            Age  Study_Hours  Final_Score
count  10.00000     10.00000    10.000000
mean   19.80000      4.60000    70.600000
std     1.75119      2.01108    11.606512
min    18.00000      2.00000    55.000000
25%    18.25000      3.25000    61.250000
50%    19.50000      4.50000    70.000000
75%    20.75000      5.75000    77.250000
max    23.00000      8.00000    90.000000

In [20]:
df = pd.read_csv('employees.csv')

In [21]:
df

     EmployeeID          Name  Department  Age  Salary
0             1    Employee_1   Marketing   23   91087
1             2    Employee_2       Sales   53   98840
2             3    Employee_3          IT   44   84384
3             4    Employee_4       Sales   43   81005
4             5    Employee_5       Sales   46   76576
..          ...           ...         ...  ...     ...
195         196  Employee_196          IT   31  106429
196         197  Employee_197     Finance   47  117922
197         198  Employee_198   Marketing   40   85766
198         199  Employee_199          IT   24   43403
199         200  Employee_200  Operations   34   62097

[200 rows x 5 columns]

In [22]:
df.info

<bound method DataFrame.info of      EmployeeID          Name  Department  Age  Salary
0             1    Employee_1   Marketing   23   91087
1             2    Employee_2       Sales   53   98840
2             3    Employee_3          IT   44   84384
3             4    Employee_4       Sales   43   81005
4             5    Employee_5       Sales   46   76576
..          ...           ...         ...  ...     ...
195         196  Employee_196          IT   31  106429
196         197  Employee_197     Finance   47  117922
197         198  Employee_198   Marketing   40   85766
198         199  Employee_199          IT   24   43403
199         200  Employee_200  Operations   34   62097

[200 rows x 5 columns]>

In [23]:
df.shape

(200, 5)

In [24]:
df.describe

<bound method NDFrame.describe of      EmployeeID          Name  Department  Age  Salary
0             1    Employee_1   Marketing   23   91087
1             2    Employee_2       Sales   53   98840
2             3    Employee_3          IT   44   84384
3             4    Employee_4       Sales   43   81005
4             5    Employee_5       Sales   46   76576
..          ...           ...         ...  ...     ...
195         196  Employee_196          IT   31  106429
196         197  Employee_197     Finance   47  117922
197         198  Employee_198   Marketing   40   85766
198         199  Employee_199          IT   24   43403
199         200  Employee_200  Operations   34   62097

[200 rows x 5 columns]>

In [25]:
df.iloc[5:6]

   EmployeeID        Name Department  Age  Salary
5           6  Employee_6    Finance   43   69353

In [27]:
df[df["Age"] > 35]

     EmployeeID          Name  Department  Age  Salary
1             2    Employee_2       Sales   53   98840
2             3    Employee_3          IT   44   84384
3             4    Employee_4       Sales   43   81005
4             5    Employee_5       Sales   46   76576
5             6    Employee_6     Finance   43   69353
..          ...           ...         ...  ...     ...
192         193  Employee_193  Operations   52  107575
193         194  Employee_194       Sales   40   36655
194         195  Employee_195          HR   48  100031
196         197  Employee_197     Finance   47  117922
197         198  Employee_198   Marketing   40   85766

[130 rows x 5 columns]

In [35]:

df[(df["Salary"] > 70000) & (df["Age"]) < 25]

     EmployeeID          Name  Department  Age  Salary
0             1    Employee_1   Marketing   23   91087
1             2    Employee_2       Sales   53   98840
2             3    Employee_3          IT   44   84384
3             4    Employee_4       Sales   43   81005
4             5    Employee_5       Sales   46   76576
..          ...           ...         ...  ...     ...
195         196  Employee_196          IT   31  106429
196         197  Employee_197     Finance   47  117922
197         198  Employee_198   Marketing   40   85766
198         199  Employee_199          IT   24   43403
199         200  Employee_200  Operations   34   62097

[200 rows x 5 columns]

In [28]:
df

     EmployeeID          Name  Department  Age  Salary
0             1    Employee_1   Marketing   23   91087
1             2    Employee_2       Sales   53   98840
2             3    Employee_3          IT   44   84384
3             4    Employee_4       Sales   43   81005
4             5    Employee_5       Sales   46   76576
..          ...           ...         ...  ...     ...
195         196  Employee_196          IT   31  106429
196         197  Employee_197     Finance   47  117922
197         198  Employee_198   Marketing   40   85766
198         199  Employee_199          IT   24   43403
199         200  Employee_200  Operations   34   62097

[200 rows x 5 columns]

In [29]:
df.groupby("EmployeeID")["Age"].mean()

EmployeeID
1      23.0
2      53.0
3      44.0
4      43.0
5      46.0
       ...
196    31.0
197    47.0
198    40.0
199    24.0
200    34.0
Name: Age, Length: 200, dtype: float64

In [30]:
df

     EmployeeID          Name  Department  Age  Salary
0             1    Employee_1   Marketing   23   91087
1             2    Employee_2       Sales   53   98840
2             3    Employee_3          IT   44   84384
3             4    Employee_4       Sales   43   81005
4             5    Employee_5       Sales   46   76576
..          ...           ...         ...  ...     ...
195         196  Employee_196          IT   31  106429
196         197  Employee_197     Finance   47  117922
197         198  Employee_198   Marketing   40   85766
198         199  Employee_199          IT   24   43403
199         200  Employee_200  Operations   34   62097

[200 rows x 5 columns]

In [37]:
df.groupby("Department")["Age"].mean()

Department
Finance       39.862069
HR            41.454545
IT            40.531250
Marketing     41.833333
Operations    41.562500
Sales         42.125000
Name: Age, dtype: float64

In [36]:
df["Salary"].max

<bound method Series.max of 0       91087
1       98840
2       84384
3       81005
4       76576
        ...
195    106429
196    117922
197     85766
198     43403
199     62097
Name: Salary, Length: 200, dtype: int64>

In [38]:
df["Age"].max

<bound method Series.max of 0      23
1      53
2      44
3      43
4      46
       ..
195    31
196    47
197    40
198    24
199    34
Name: Age, Length: 200, dtype: int64>

In [39]:
df.groupby("Department").agg({'Age' : 'max' })

            Age
Department
Finance      57
HR           59
IT           58
Marketing    58
Operations   59
Sales        58

In [40]:
df.groupby("Salary").size()

Salary
30301     1
30854     1
31802     1
32049     1
32200     1
         ..
118614    1
118891    1
119045    1
119474    1
119912    1
Length: 200, dtype: int64

In [41]:
missing_value = df.isnull()

In [42]:
print(missing_value)

     EmployeeID   Name  Department    Age  Salary
0         False  False       False  False   False
1         False  False       False  False   False
2         False  False       False  False   False
3         False  False       False  False   False
4         False  False       False  False   False
..          ...    ...         ...    ...     ...
195       False  False       False  False   False
196       False  False       False  False   False
197       False  False       False  False   False
198       False  False       False  False   False
199       False  False       False  False   False

[200 rows x 5 columns]

In [43]:
df.isnull().sum()

EmployeeID    0
Name          0
Department    0
Age           0
Salary        0
dtype: int64

In [103]:
df

     EmployeeID          Name  Department  Age  Salary
0             1    Employee_1   Marketing   23   91087
1             2    Employee_2       Sales   53   98840
2             3    Employee_3          IT   44   84384
3             4    Employee_4       Sales   43   81005
4             5    Employee_5       Sales   46   76576
..          ...           ...         ...  ...     ...
195         196  Employee_196          IT   31  106429
196         197  Employee_197     Finance   47  117922
197         198  Employee_198   Marketing   40   85766
198         199  Employee_199          IT   24   43403
199         200  Employee_200  Operations   34   62097

[200 rows x 5 columns]

In [45]:
df.iloc[2]["Age"] = 50

C:\Users\avd09\AppData\Local\Temp\ipykernel_3544\3516588554.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.iloc[2]["Age"] = 50

In [46]:
laddo = df.copy()

In [47]:
print(laddo)

     EmployeeID          Name  Department  Age  Salary
0             1    Employee_1   Marketing   23   91087
1             2    Employee_2       Sales   53   98840
2             3    Employee_3          IT   44   84384
3             4    Employee_4       Sales   43   81005
4             5    Employee_5       Sales   46   76576
..          ...           ...         ...  ...     ...
195         196  Employee_196          IT   31  106429
196         197  Employee_197     Finance   47  117922
197         198  Employee_198   Marketing   40   85766
198         199  Employee_199          IT   24   43403
199         200  Employee_200  Operations   34   62097

[200 rows x 5 columns]

In [48]:
df.dropna(axis=0)

     EmployeeID          Name  Department  Age  Salary
0             1    Employee_1   Marketing   23   91087
1             2    Employee_2       Sales   53   98840
2             3    Employee_3          IT   44   84384
3             4    Employee_4       Sales   43   81005
4             5    Employee_5       Sales   46   76576
..          ...           ...         ...  ...     ...
195         196  Employee_196          IT   31  106429
196         197  Employee_197     Finance   47  117922
197         198  Employee_198   Marketing   40   85766
198         199  Employee_199          IT   24   43403
199         200  Employee_200  Operations   34   62097

[200 rows x 5 columns]

In [111]:
df.dropna(axis=1)

     EmployeeID          Name  Department  Age  Salary
0             1    Employee_1   Marketing   23   91087
1             2    Employee_2       Sales   53   98840
2             3    Employee_3          IT   44   84384
3             4    Employee_4       Sales   43   81005
4             5    Employee_5       Sales   46   76576
..          ...           ...         ...  ...     ...
195         196  Employee_196          IT   31  106429
196         197  Employee_197     Finance   47  117922
197         198  Employee_198   Marketing   40   85766
198         199  Employee_199          IT   24   43403
199         200  Employee_200  Operations   34   62097

[200 rows x 5 columns]